### ISSUE TITLE
unique properties only inside single file

### ISSUE THREAD

**Issue by wilx** [mikkoi/maven-enforcer-property-usage#1]
I have been looking around for Maven Enforcer rule that would _check multiple files for duplicate properties within a single file_. Your rule can enforce unique properties across multiple files but to check only within a single file I have to, it seems, specify the rule with each file specifically. Or is there a way to use your Maven Rule to do the check that I want?

**Comment by mikkoi** [comment]
Do you mean *check multiple **.properties** files* for duplicate definitions?
At the moment, this is not possible.
But I see no reason why this rule couldn't do what you need.

**Comment by wilx** [comment]
I am basically trying to check for botched merges that happened few times here where the some property file line got duplicated. I want to check for internal consistency of individual .properties files.

**Comment by mikkoi** [comment]
I understand. Thank you for writing about the merges. It's clear now what is needed.
I'll see if I can improve it to do that.
I cannot promise any schedule, sorry.

**Comment by mikkoi** [comment]
Hi, just release version 0.0.4.
Now with more reporting.
Please tell me what you think. Thank you.

**Comment by mikkoi** [comment]
More reporting added to version 0.0.4.
